hash-format = "sha256"

[[files]]
file = "config/.keep"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/servux.json"
hash = "bb54df2552f5267e473097ab8bdb99bbc9aa34a191d9fc5b3ec137728e036f65"

[[files]]
file = "mods/badpackets.pw.toml"
hash = "ab608dc348e5a47bc1005c04925140942feeb2519f5ed6a9b01be74da790835b"
metafile = true

[[files]]
file = "mods/better-suggestions.pw.toml"
hash = "81b96b47638d2e35d3335628ce49315d6d122dbb5c052e6a3168c5ca958e2709"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "2c912bceb71760927f62a82238e320e6eccaa57383d8f0db9e729b4b6dd5e063"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "7c6498f598f7a71d7d285b87ab44383e3be1eed32330aaa7d0e4ff5332256346"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "547fcb6481c2cf682b9de98f0a719d27f0ba896d7b06076f2135f2abd470aea6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "dae294bc7e60c5052b3c705bc15e4b2ebc1af7465e294c4f9824a4b63719475b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "8d40436970d9adcfe3c0b72c9f0cd1af217948469b091b0f07ca3df187ce2e61"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e26dacab5ed497b7bf6500e389eba5e21cd4b9d7b38089045cd26818a4d2f589"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "143c142b7ff72c55425156edac3c7328b664d99dda2f1c6a1dee399d7f51a833"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "76e5afe777819136bdc78140baa629f4ca3c2db68c6713d5e336af125fb21595"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a63765eb780a36cd968e2777d2c20bea5e5ca3ccdd920e64964e3746cf2a7f0d"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "87c4d42219d3aea70af7aa016e0e4bdfac94d2a4ece9e719e8e84e9203735300"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "be165c98a6b6878a158d7d0606f68bf2c8e59cde8b95455d4b872c82f0041fc8"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "a798fe73c6b08201687d4cd067a5617624cf743145fca8fea579b65949944cae"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "c4defe486d9d73ab56a8b46bac12a5d9076fc6c99b7e6674a690cb94bdc6e73f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "3ef916454266cdbcbd3f517c53b1e27b360caa5266bf1b44d0d627aeab643516"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "9a1695184cdb4646ae5deef3ed576e7dc1235cff1ff20493aa482a2c512928b0"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "305e286ce8213886bb80d026451f1695cfd681d4f5d643bba3933b3e1120a998"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "b915a285a111e65aed4ad2ce81be613040e9285caca1b2ef6b88ed639f811670"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d72a8ffcacdd19e6d71eccb4b112cf763bf75b2c438506e01ab0aa76e91c6325"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "f3b0dc8728401319a897b51835b2b65898dc3b769aa1f1ed0a1f513bd91c409a"
metafile = true

[[files]]
file = "pack-instance.sh"
hash = "9ac81aa5013dcbfb39d98a391220ffb1e7ca382988134cd8052e37d033bf09c7"

[[files]]
file = "pack-instance.toml"
hash = "5d5a19b267e39cb1d093ccdfd776ab2db6f5b7f62fff7aeff3a2f842e7f02acd"
