name = "Server Mods"
author = "Michael Pennington"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c841b6c1b89f7cae1a1eb2208a6dc0d4e4e1b06d7877df124c6dcc53a0b24bcf"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
